server:
  port: 8080
spring:
  application:
    name: REST-API-for-User-Management
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/user_management
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
    web: debug